# action.yml
name: 'Parse latest issue body'
description: 'Grab body of latest issue'
inputs:
  repo_name:
    description: 'In the format of <org>/<repo>'
    required: true
    default: 'joe/hudson'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo_name }}
