on:
  issues:
    types: [opened]

jobs:
  issue_parser:
    runs-on: ubuntu-latest
    name: Grab body of latest issue
    steps:
    - name: Parse latest GitHub issue
      uses: daniyalj/ga-hello-world
      with:
        repo-name: 'ga-hello-world'
