on:
  issues:
    types: [opened]

jobs:
  issue_parser:
    runs-on: ubuntu-latest
    name: Grab body of latest issue
    steps:
    - name: Parse latest GitHub issue
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: daniyalj/ga-hello-world@master
      with:
        repo_name: 'daniyalj/ga-hello-world'
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
